name: workflow.yml
on:
  push:
    branches:
      - master

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Install required tools
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          dotnet tool install -g dotnet-stryker

      - name: Run unit tests
        run: |
          dotnet test --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutput=./TestResults/Coverage/ \
            /p:CoverletOutputFormat=cobertura
        
      - name: Generate report
        run: |
          reportgenerator \
            -reports:"coverage.xml" \
            -targetdir:"coverage-report" \
            -reporttypes:Html

      - name: Run Mutation Tests
        run: |
          dotnet stryker --threshold-high 80 --threshold-low 80 --threshold-break 80 --report html

      - name: Collect Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report
          if-no-files-found: 'warn'

      - name: Collect Stryker Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stryker-report
          path: StrykerOutput
          if-no-files-found: 'warn'
    